version: '3'

services:
  web:
    image: frota-front-rastreio
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
