services:
  front-rastreio:
    container_name: front-rastreio
    image: frota-front-rastreio
    build:
      context: .
      args:
      # URL LADO CLIENTE (Precisa estar certo no build)
        - NEXT_PUBLIC_API_URL=https://erick-3000.code.fslab.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=https://erick-3000.code.fslab.dev
    #restart: always