// app/layout.js
import ReactQueryProvider from '@/providers/reactQueryProvider';
import 'leaflet/dist/leaflet.css';
import './globals.css'; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
       <ReactQueryProvider>
        <body className='bg-gradient-to-b from-[#6A89CC] to-[#82CCDD]'>
          {children}
        </body>
       </ReactQueryProvider>
    </html>
  );
}